V4.2.0 rc
RaaLabs/Connectors.Terasaki pull request #21
Opened 2022-08-23 10:25 UTC by srudaa

## Summary

### Changed

- Custom TCP connector is switched out to use the Sockets module in the framework. 
- Alpine docker image is building binary instead. This reduces the image size. 

### Fixed

- Able to deal with asterisk chars in the payload.

2022-08-23 10:49 UTC, rafaelschlatter requested changes
Nice, code is simpler with the Sockets module. One inline comment. PR needs a label to create a new version (will be 4.3.0 if minor, 4.2.0 already exists).

2022-08-23 10:49 UTC, rafaelschlatter commented on Source/SentenceParser.cs
> +            var calculatedChecksum = sentence.Substring(0, sentence.LastIndexOf("*", StringComparison.Ordinal)).Aggregate((byte)0x00, (sum, next) => (byte)(sum ^ next));
`state` is not used and can be named `_` (line 47, but cant add lines to code that is not in diff -.-)

2022-08-31 12:48 UTC, rafaelschlatter commented
@srudaa should we include batching in this PR?

2022-08-31 15:56 UTC, srudaa commented
> @srudaa should we include batching in this PR?

No, let's create a separate one for that.

2022-11-15 08:00 UTC, rafaelschlatter approved these changes

2022-11-15 08:00 UTC, rafaelschlatter commented
@thotokraa could you take a look at this PR?

2022-11-15 08:02 UTC, merged